version: "3.9"

services:
  fitness-api:
    build:
      context: ./src/FitnessTracker.Api
      dockerfile: Dockerfile
    container_name: fitness-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
